name    'puppet-archmngt'
version '1.0.0'
source 'https://github.com/akquinet/puppet-archmngt'
author 'saheba'
license 'Apache2'
summary 'puppet module to encapsulate OS-specific archive management commands like tar and zip'
description 'this module helps to deal with archive files in puppet scripts'
project_page 'http://www.akquinet.de/java/entwicklungsinfrastrukturen.html'
